name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Script
        run: |
          echo "Starting deployment on self-hosted runner..."
          
          # Move to the existing project directory on the server
          cd /home/sw/WaterMarking-Lab
          
          echo "Pulling latest code..."
          git pull origin main
          
          echo "Rebuilding and restarting Docker containers..."
          cd backend
          
          # 'sw' user is in docker group, so sudo is not needed
          docker-compose down
          docker-compose up -d --build
          
          echo "Cleaning up unused images..."
          docker image prune -f
          echo "Deployment finished successfully!"
